USE bd_laby

CREATE TABLE STANOWISKA(
    NAZWA VARCHAR(20) PRIMARY KEY ,
    POZIOM_DOSTEPU SMALLINT NOT NULL CHECK(POZIOM_DOSTEPU BETWEEN 0 AND 2)
)

CREATE TABLE PLACOWKI(
    NAZWA VARCHAR(20) PRIMARY KEY,
    ILOSC_SUROWCA DECIMAL(4, 2) CHECK (ILOSC_SUROWCA BETWEEN 0 AND 1000),
    KOD_POCZTOWY CHAR(6) NOT NULL CHECK (KOD_POCZTOWY LIKE '[0-9][0-9]-[0-9][0-9][0-9]'),
    ULICA VARCHAR(30) NOT NULL,
    NUMER_BUDYNKU INT NOT NULL CHECK(NUMER_BUDYNKU BETWEEN 0 AND 999)
)

CREATE TABLE FIRMY_TRANSPORTOWE(
    NAZWA VARCHAR(40) PRIMARY KEY,
    NUMER_TELEFONU CHAR(9) CHECK (NUMER_TELEFONU LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') UNIQUE,
    EMAIL VARCHAR(30) NOT NULL CHECK (EMAIL LIKE '%@%') UNIQUE
)

CREATE TABLE PRACOWNICY(
    ID_PRACOWNIKA INT IDENTITY(1,1) PRIMARY KEY,
    IMIE VARCHAR(20) NOT NULL CHECK (IMIE LIKE '[A-Z]%'),
    NAZWISKO VARCHAR(30) NOT NULL CHECK (NAZWISKO LIKE '[A-Z]%'),
    EMAIL VARCHAR(30) NOT NULL CHECK (EMAIL LIKE '%@%') UNIQUE,
    CZY_PRACUJE BIT NOT NULL,
    PRZELOZONY INT FOREIGN KEY REFERENCES PRACOWNICY(ID_PRACOWNIKA) ON DELETE NO ACTION,
    MIEJSCE_PRACY VARCHAR(20) FOREIGN KEY REFERENCES PLACOWKI(NAZWA) ON UPDATE CASCADE ON DELETE CASCADE,
    STANOWISKO VARCHAR(20) FOREIGN KEY REFERENCES STANOWISKA(NAZWA) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE ZAMOWIENIA_NA_ZLOTO(
    ID_ZAMOWIENIA INT IDENTITY(1,1) PRIMARY KEY,
    [DATA] DATE NOT NULL,
    KOSZT DECIMAL(6,2) NOT NULL CHECK (KOSZT BETWEEN 0.0 AND 200000.0),
    [STATUS] VARCHAR(20) NOT NULL CHECK ([STATUS] IN ('przyjęte', 'w realizacji', 'dostarczane', 'zrealizowane')),
    ILOSC DECIMAL(3,2) NOT NULL CHECK (ILOSC BETWEEN 0.0 AND 500.0),
    DOSTARCZANA_DO VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES PLACOWKI(NAZWA) ON UPDATE CASCADE,
    FIRMA_TRANSPORTOWA VARCHAR(40) NOT NULL FOREIGN KEY REFERENCES FIRMY_TRANSPORTOWE(NAZWA) ON UPDATE CASCADE 
)

CREATE TABLE PARTIE_SUROWCA(
    ID_PARTII INT IDENTITY(1,1) PRIMARY KEY,
    WAGA DECIMAL(3,2) CHECK (WAGA BETWEEN 0.0 AND 100.0),
    DATA_DOSTAWY DATE,
    ZAMOWIENIE INT FOREIGN KEY REFERENCES ZAMOWIENIA_NA_ZLOTO(ID_ZAMOWIENIA)
)

CREATE TABLE PRODUKTY(
    NAZWA VARCHAR(20) PRIMARY KEY,
    KOSZT_PRODUKCJI DECIMAL(4,2) NOT NULL CHECK (KOSZT_PRODUKCJI BETWEEN 0.0 AND 5000.0),
    CENA_SPRZEDAZY DECIMAL(5,2) CHECK (CENA_SPRZEDAZY BETWEEN 0.0 AND 25000.0),
    ILOSC_SUROWCA_POTRZEBNA_DO_WYPRODUKOWANIA DECIMAL(2,2) NOT NULL CHECK (ILOSC_SUROWCA_POTRZEBNA_DO_WYPRODUKOWANIA BETWEEN 0.0 AND 15.0),
    ILOSC TINYINT CHECK (ILOSC BETWEEN 0 AND 100),
    CZY_PRODUKOWANY BIT NOT NULL,
    MARZA VARCHAR(6) CHECK (MARZA LIKE '%[0-9]%' AND RIGHT(MARZA, 1) = '%' AND TRY_CAST(LEFT(MARZA, LEN(MARZA)-1) AS INT) BETWEEN 0 AND 5000),
    MIEJSCE_SKLADOWANIA VARCHAR(20) FOREIGN KEY REFERENCES PLACOWKI(NAZWA) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE KLIENCI(
    NIP CHAR(10) PRIMARY KEY CHECK (NIP LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    NAZWA CHAR(20) NOT NULL UNIQUE,
    EMAIL VARCHAR(30) NOT NULL CHECK (EMAIL LIKE '%@%') UNIQUE,
    NUMER_TELEFONU CHAR(9) CHECK (NUMER_TELEFONU LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') UNIQUE
)

CREATE TABLE ZAMOWIENIA_NA_PRODUKTY(
    ID_ZAMOWIENIA INT IDENTITY(1,1) PRIMARY KEY,
    [DATA] DATE NOT NULL,
    [STATUS] VARCHAR(20) NOT NULL CHECK ([STATUS] IN ('przyjęte', 'anulowane', 'w realizacji', 'zrealizowane')),
    KLIENT CHAR(10) NOT NULL FOREIGN KEY REFERENCES KLIENCI(NIP)
)

CREATE TABLE ZAMOWIONE_PRODUKTY(
    ID_PRODUKTU VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES PRODUKTY(NAZWA) ON UPDATE CASCADE,
    ID_ZAMOWIENIA INT NOT NULL FOREIGN KEY REFERENCES ZAMOWIENIA_NA_PRODUKTY(ID_ZAMOWIENIA),
    PRIMARY KEY (ID_PRODUKTU, ID_ZAMOWIENIA),
    ILOSC TINYINT NOT NULL CHECK(ILOSC BETWEEN 0 AND 50)
)