USE bd_laby;

-- [1]
-- Sugestia: Wydatki miesieczne na zloto w 2024.
-- Modyfikacja: Brak. 
SELECT 
    FORMAT([DATA], 'yyyy-MM') AS miesiac,
    SUM(KOSZT) AS koszta
FROM ZAMOWIENIA_NA_ZLOTO
WHERE YEAR([DATA])=2024
GROUP BY FORMAT([DATA], 'yyyy-MM')
ORDER BY miesiac ASC;

-- [2]
-- Sugestia: Pracownicy, ktorzy nie pracuja ale nadal maja dostep do bazy danych.
-- Modyfikacja: Brak.
SELECT 
    IMIE, 
    NAZWISKO,
    STANOWISKO
FROM PRACOWNICY
JOIN STANOWISKA ON PRACOWNICY.STANOWISKO = STANOWISKA.NAZWA
WHERE PRACOWNICY.CZY_PRACUJE = 0
AND PRACOWNICY.STANOWISKO IS NOT NULL
ORDER BY IMIE, NAZWISKO;

-- [3]
-- Sugestia: 5 klientow z najwieksza suma z zamowien w 2024
-- Modyfikacja: Przez ostatnie 10 lat, >=2014
SELECT TOP 5 
    KLIENCI.NAZWA AS nazwa_klienta,
    SUM(PRODUKTY.CENA_SPRZEDAZY * ZAMOWIONE_PRODUKTY.ILOSC) AS ile_wydal
FROM KLIENCI 
JOIN ZAMOWIENIA_NA_PRODUKTY ON KLIENCI.NIP = ZAMOWIENIA_NA_PRODUKTY.KLIENT
JOIN ZAMOWIONE_PRODUKTY ON ZAMOWIENIA_NA_PRODUKTY.ID_ZAMOWIENIA = ZAMOWIONE_PRODUKTY.ID_ZAMOWIENIA
JOIN PRODUKTY ON ZAMOWIONE_PRODUKTY.ID_PRODUKTU = PRODUKTY.NAZWA
WHERE YEAR(ZAMOWIENIA_NA_PRODUKTY.[DATA]) >= 2014
AND ZAMOWIENIA_NA_PRODUKTY.[STATUS] = 'zrealizowane'
GROUP BY KLIENCI.NAZWA
ORDER BY ile_wydal DESC;

-- [4]
-- Autorskie: Suma zrealizowanych zyskow z zamowień/wypelnienia umow w ostatnich 4 miesiacach
-- Modyfikacja: Suma dochodow i suma wydatkow ze zrealizowanych zamowien / "dostarczonych" dostaw w poprzednim kwartale
WITH kwartal AS 
( SELECT DATEADD(QUARTER, -1, GETDATE()) AS data_poczatkowa, GETDATE() AS data_koncowa )
SELECT 
    SUM(PRODUKTY.CENA_SPRZEDAZY * ZAMOWIONE_PRODUKTY.ILOSC) AS dochody,
    SUM(ZAMOWIENIA_NA_ZLOTO.KOSZT) AS wydatki
FROM ZAMOWIENIA_NA_PRODUKTY
JOIN ZAMOWIONE_PRODUKTY ON ZAMOWIENIA_NA_PRODUKTY.ID_ZAMOWIENIA = ZAMOWIONE_PRODUKTY.ID_ZAMOWIENIA
JOIN PRODUKTY ON ZAMOWIONE_PRODUKTY.ID_PRODUKTU = PRODUKTY.NAZWA
JOIN ZAMOWIENIA_NA_ZLOTO ON ZAMOWIENIA_NA_ZLOTO.DATA BETWEEN 
    (SELECT data_poczatkowa FROM kwartal) AND (SELECT data_koncowa FROM kwartal)
WHERE ZAMOWIENIA_NA_PRODUKTY.[DATA] BETWEEN 
    (SELECT data_poczatkowa FROM kwartal) AND (SELECT data_koncowa FROM kwartal)
AND ZAMOWIENIA_NA_PRODUKTY.[STATUS] = 'zrealizowane'

-- [5]
-- Autorskie: 
-- Modyfikacja: 
SELECT
    FORMAT(ZAMOWIENIA_NA_PRODUKTY.[DATA], 'yyyy-MM') AS miesiac,
    SUM(PRODUKTY.ILOSC_SUROWCA_POTRZEBNA_DO_WYPRODUKOWANIA * ZAMOWIONE_PRODUKTY.ILOSC) AS TotalRawMaterialUsed
FROM ZAMOWIENIA_NA_PRODUKTY
JOIN ZAMOWIONE_PRODUKTY ON ZAMOWIENIA_NA_PRODUKTY.ID_ZAMOWIENIA = ZAMOWIONE_PRODUKTY.ID_ZAMOWIENIA
JOIN PRODUKTY ON ZAMOWIONE_PRODUKTY.ID_PRODUKTU = PRODUKTY.NAZWA
WHERE ZAMOWIENIA_NA_PRODUKTY.[STATUS] = 'zrealizowane'
GROUP BY FORMAT(ZAMOWIENIA_NA_PRODUKTY.[DATA], 'yyyy-MM')
HAVING SUM(PRODUKTY.ILOSC_SUROWCA_POTRZEBNA_DO_WYPRODUKOWANIA * ZAMOWIONE_PRODUKTY.ILOSC) > 100;

-- [6]
-- Autorskie: Ilu pracownikow podlega osobie obejmujacej stanowisko w systemie
-- Modyfikacja: Brak.
SELECT 
    PRZELOZENI.IMIE AS imie,
    PRZELOZENI.NAZWISKO AS nazwisko,
    COUNT(PRACOWNICY_1.ID_PRACOWNIKA) AS ilosc_pracownikow,
    PRZELOZENI.STANOWISKO AS obejmowane_stanowisko
FROM PRACOWNICY PRACOWNICY_1
JOIN PRACOWNICY PRZELOZENI ON PRACOWNICY_1.PRZELOZONY = PRZELOZENI.ID_PRACOWNIKA
WHERE PRACOWNICY_1.CZY_PRACUJE = 1
GROUP BY PRZELOZENI.IMIE, PRZELOZENI.NAZWISKO, PRZELOZENI.STANOWISKO
ORDER BY ilosc_pracownikow DESC;

-- [7]
-- Autorskie: 5 produktow z najlepsza marża
-- Modyfikacja: 
GO
CREATE VIEW ActiveProductsWithMargin
( nazwa_produktu, marza )
    AS SELECT PRODUKTY.NAZWA,
    CAST(REPLACE(PRODUKTY.MARZA, '%', '') AS INT) AS marza
FROM PRODUKTY
WHERE PRODUKTY.CZY_PRODUKOWANY = 1
GO

SELECT TOP 5
    nazwa_produktu,
    marza
FROM ActiveProductsWithMargin
ORDER BY marza DESC

DROP VIEW ActiveProductsWithMargin;

-- [8]
-- Autorskie: Ile powinno być surowca w warsztacie
-- Modyfikacja: 
SELECT
    PLACOWKI.NAZWA AS miejsce,
    SUM(ZAMOWIENIA_NA_ZLOTO.ILOSC) AS ile_kupione,
    SUM(PRODUKTY.ILOSC_SUROWCA_POTRZEBNA_DO_WYPRODUKOWANIA * PRODUKTY.ILOSC) AS ile_zuzyto,
    SUM(ZAMOWIENIA_NA_ZLOTO.ILOSC) - SUM(PRODUKTY.ILOSC_SUROWCA_POTRZEBNA_DO_WYPRODUKOWANIA * PRODUKTY.ILOSC) AS ile_powinno_byc
FROM ZAMOWIENIA_NA_ZLOTO
JOIN PLACOWKI ON ZAMOWIENIA_NA_ZLOTO.DOSTARCZANA_DO = PLACOWKI.NAZWA
JOIN PRODUKTY ON PLACOWKI.NAZWA = PRODUKTY.MIEJSCE_SKLADOWANIA
WHERE PLACOWKI.NAZWA = 'Warsztat'
GROUP BY PLACOWKI.NAZWA;
