USE bd_laby
--usuwanie zaleznosci
ALTER TABLE ZAMOWIONE_PRODUKTY NOCHECK CONSTRAINT ALL
ALTER TABLE ZAMOWIENIA_NA_PRODUKTY NOCHECK CONSTRAINT ALL
ALTER TABLE PRODUKTY NOCHECK CONSTRAINT ALL
ALTER TABLE PARTIE_SUROWCA NOCHECK CONSTRAINT ALL
ALTER TABLE ZAMOWIENIA_NA_ZLOTO NOCHECK CONSTRAINT ALL
ALTER TABLE PRACOWNICY NOCHECK CONSTRAINT ALL
ALTER TABLE KLIENCI NOCHECK CONSTRAINT ALL
ALTER TABLE FIRMY_TRANSPORTOWE NOCHECK CONSTRAINT ALL
ALTER TABLE PLACOWKI NOCHECK CONSTRAINT ALL
ALTER TABLE STANOWISKA NOCHECK CONSTRAINT ALL
--usuwanie tabel
DROP TABLE IF EXISTS ZAMOWIONE_PRODUKTY
DROP TABLE IF EXISTS ZAMOWIENIA_NA_PRODUKTY
DROP TABLE IF EXISTS PRODUKTY
DROP TABLE IF EXISTS PARTIE_SUROWCA
DROP TABLE IF EXISTS ZAMOWIENIA_NA_ZLOTO
DROP TABLE IF EXISTS PRACOWNICY
DROP TABLE IF EXISTS KLIENCI
DROP TABLE IF EXISTS FIRMY_TRANSPORTOWE
DROP TABLE IF EXISTS PLACOWKI
DROP TABLE IF EXISTS STANOWISKA